id = "puppet-grammar"
name = "puppet Grammar"
version = "0.0.1"
schema_version = 1
authors = ["Stefan Maier <stefanmaier@gmail.com>"]
description = "My cool extension"
repository = "https://github.com/tliff/rust-grammar"
languages = ["languages/puppet"]

[grammars.puppet]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-puppet"
rev = "15f192929b7d317f5914de2b4accd37b349182a6"

